apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmr-agent-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmr-agent-b
  template:
    metadata:
      labels:
        app: dmr-agent-b
    spec:
      containers:
        - name: dmr-agent
          image: {{ .Values.dmrAgents.agentB.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.dmrAgents.agentB.port }}
          env:
            - name: PORT
              value: "{{ .Values.dmrAgents.agentB.port }}"
            - name: ENVIRONMENT
              value: "{{ .Values.shared.environment }}"
            - name: LOGGER_COLORS
              value: "true"
            - name: LOGGER_LOG_LEVELS
              value: "error,warn,log,debug"
            - name: DMR_SERVER_WEBSOCKET_URL
              value: "http://dmr-server:{{ .Values.dmrServer.port }}"
            - name: WEBSOCKET_RECONNECTION_DELAY
              value: "1000"
            - name: WEBSOCKET_RECONNECTION_DELAY_MAX
              value: "5000"
            - name: AGENT_PRIVATE_KEY
              value: {{ .Values.dmrAgents.agentA.privateKey | quote }}
            - name: AGENT_ID
              value: {{ .Values.dmrAgents.agentA.id | quote }}
            - name: OUTGOING_MESSAGE_ENDPOINT
              value: {{ .Values.shared.outgoingEndpoint | quote }}
            - name: MESSAGE_DELIVERY_TIMEOUT_MS
              value: "2000"
