apiVersion: v1
kind: Service
metadata:
  name: dmr-server
spec:
  selector:
    app: dmr-server
  ports:
    - port: {{ .Values.dmrServer.port }}
      targetPort: {{ .Values.dmrServer.port }}
  type: ClusterIP
