apiVersion: v1
kind: Service
metadata:
  name: dmr-agent-a
spec:
  selector:
    app: dmr-agent-a
  ports:
    - port: {{ .Values.dmrAgents.agentA.port }}
      targetPort: {{ .Values.dmrAgents.agentA.port }}
  type: ClusterIP
