name: Auto Format Dependabot PR

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev

jobs:
  auto-format:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/setup

      - run: pnpm format

      - name: Commit files
        run: |
          git config --local user.name "dependabot-autoformat"
          git config --local user.email "action@github.com"
          git add .
          git commit -a -m "chore: autoformat (via CI)"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
