name: Run check
on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      working-directory:
        required: true
        type: string

jobs:
  check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.working-directory }}/package.json
          cache: pnpm
          cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml
      - run: pnpm install
      - run: ${{ inputs.command }}
